### ISSUE TITLE
Rename this repo to pulp_certguard

### ISSUE THREAD

**Issue by rochacbruno** [pulp/pulp-certguard#12]
All other plugins are named using `_` like `pulp_rpm`, `pulp_file`, `pulp_python`, `pulp_docker` but this uses `-` and this makes hard to automate installation based on name/label.

I suggest renaming to `pulp_certguard` (github will redirect old name)

**Comment by rochacbruno** [comment]
@bmbouter

**Comment by rochacbruno** [comment]
*also I just figures out that this repo should not allow opening issues :)

**Comment by bmbouter** [comment]
More recently pulpcore-plugin became the plugin repository's github name so we already have some inconsistency. Here's the reasoning to keep the - and we can see if it makes sense. URLs on PyPI replace a _ with a -  but github (obviously) does not. Like this one: https://pypi.org/project/pulpcore_plugin/

So for consistency between the PyPI and github project name/url I think the - is more favorable. So rather than call it pulp_certguard on github and pulp-certguard on PyPI we can call them all pulp-certguard. Naming plugins like pulp_ansible as pulp-ansible would make more sense to me. @rochacbruno what do you think?

I agree we should disable comments here.
